# Node.js with React

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages: 
 - stage: Build
  steps:
    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'
