# Master Monolithic Pipeline

trigger:
  - master

stages:
  - stage: Configure
    jobs:
      - job: Setup
        pool:
          vmImage: 'Ubuntu-16.04' # defines runtime

  - stage: Testing
    jobs:
      - job: Run_Tests
        steps:
          - script: |
              npm install
              npm run test
            displayName: 'Running Test'
